App\ApiResource\Order:
    operations:
        ApiPlatform\Metadata\Post:
            uriTemplate: 'calculate-price'
            status: 200
            write: false
            controller: App\Controller\CalculatePriceAction
            output: App\DTO\Price
            openapi:
                description: Calculates price
