App\ApiResource\Purchase:
    operations:
        ApiPlatform\Metadata\Post:
            uriTemplate: 'purchase'
            status: 200
            write: false
            controller: App\Controller\PurchaseAction
            output: App\DTO\EmptyResponse
            openapi:
                description: Provides purchase
