#!/usr/bin/env sh
curl \
    -X POST \
    https://localhost/api/purchase \
    --insecure \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    -d '{"product": 1, "taxNumber": "GR123456789", "couponCode": "D15", "paymentProcessor": "paypal"}'
